version: '3.3'
services:
  mysql:
    image: postgres:latest
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgresql
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=app
        
